services:
  db:
    image: postgres:15-alpine
    container_name: ep_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: everyplate_db
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ./init_prod.sql:/docker-entrypoint-initdb.d/init_prod.sql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ep_fastapi_prod
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/everyplate_db
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "127.0.0.1:8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${BACKEND_URL}
    container_name: ep_vue_prod
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - backend

volumes:
  pgdata_prod: