services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Hot-reloading
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/everyplate_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: everyplate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: